### PR TITLE
set sender gid for event created in EventDeliveryManager::deliver_events_5g_

### LINKED ISSUE #75: Assertion thrown when simulating with ginzburg_neuron and mcculloch_pitts_neuron
Running the code snippet
```
import nest

nest.ResetKernel()

n1 = nest.Create("ginzburg_neuron")
n2 = nest.Create("mcculloch_pitts_neuron")

nest.Connect(n1, n2, syn_spec={"weight": 1.0})

nest.Simulate(100.)
```
leads to an assertion being thrown. I discovered this while looking at the examples, and saw that `correlospinmatrix_detector_two_neuron.py` failed.

The assertion happens because of the `handle( SpikeEvent& e )` function to the `binary_neuron`, which both `ginzburg_neuron` and `mcculloch_pitts_neuron` are derived from. The `handle` function calls
```
long gid = e.get_sender_gid();
```
which calls
```
inline index
Event::get_sender_gid( void ) const
{
  assert( sender_gid_ > 0 );
  return sender_gid_;
}
```
and the `sender_gid_` is set to be 0 for some reason. The strange thing is that `EventDeliveryManager` actually set the correct `sender_gid` in its [`send` function](https://github.com/jakobj/nest-simulator/blob/5g/nestkernel/event_delivery_manager_impl.h#L64), but I haven't figured out where things go wrong.

I can make a regression test for this and try to look more into it.

### PR DESCRIPTION
**Pull request by stinebuu**
This PR fixes #75.

As far as I understand, when a `SpikeEvent` is sent (or delivered to?) a `binary_neuron` we call `deliver_events_5g_` which creates a `SpikeEvent`, set `syn_id` and `lcid` to the event, then sends the `SpikeEvent` with `ConnectionManager::send_5g`. Here, we directly send the event along to the appropriate synapse. Several values are then set before the event is eventually sent to the appropriate `handle` function. However `sender_gid` was never set, and we therefore get the assertion error reported in #75, because `get_sender_gid()` eventually gets called and we of course do not have a sender gid properly set in the `Event` class. 

So, this PR sets the sender gid! I did it in `deliver_events_5g_`, and hope I have used the correct function to find the source gid.

I was unsure about whether the test should be a unittest or regressiontest. I have placed it in the unittest folder, but can of course move it.

### CODE REVIEW

File: nestkernel/event_delivery_manager.cpp [hunk 1]
```diff
@@ -701,8 +701,14 @@ EventDeliveryManager::deliver_events_5g_( const thread tid,
       {
         se.set_stamp( prepared_timestamps[ spike_data.get_lag() ] );
         se.set_offset( spike_data.get_offset() );
-        kernel().connection_manager.send_5g(
-          tid, spike_data.get_syn_id(), spike_data.get_lcid(), cm, se );
+
+        index syn_id = spike_data.get_syn_id();
```
Comment (jakobj) [inline nestkernel/event_delivery_manager.cpp]: these could be `const`

**Comment by stinebuu** [comment]
@jakobj I have now added a check in `SourceTable::get_gid`. I had to move the function from the .h file to the .cpp file to do so. Using `SourceTable::get_gid` would be wrong for all models if `keep_source_table` is `false`, right? Or should I still check if we are using binary neurons before I throw the exception?
